#!/bin/sh
# OpenJDK BUILD_CXX on Darwin; see darwin-build-cc.
set -eu
case "${1:-}" in
  --version|-v)
    echo "g++ (GCC) 14.1.0"
    echo "Copyright (C) 2024 Free Software Foundation, Inc."
    echo "This is free software; see the source for copying conditions.  There is NO"
    echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
    exit 0
    ;;
  -dumpversion)
    echo "14.1.0"
    exit 0
    ;;
esac
args=
for a in "$@"; do
  case "$a" in
    -static-libgcc|-static-libstdc++|--disable-new-dtags|-Wl,--*|-Wl,-z,*) ;;
    *) args="$args $a" ;;
  esac
done
# shellcheck disable=SC2086
exec /usr/bin/clang++ $args
